In [ ]:
### S9-1.1 Claculadora del indice de masa corporal.

def calculadora_imc(peso, altura):
    valor_imc = peso / altura**2 
    return valor_imc

def clasificador_de_resultado(valor_imc):
    if valor_imc < 18.5:
        return f"Tu índice de masa corporal es {valor_imc:.1f}, tienes un peso bajo."
    elif valor_imc <= 24.9:
        return f"Tu índice de masa corporal es {valor_imc:.1f}, tienes un peso normal."
    elif valor_imc <= 29.9:
        return f"Tu índice de masa corporal es {valor_imc:.1f}, tienes sobrepeso."
    else:
        return f"Tu índice de masa corporal es {valor_imc:.1f}, tienes obesidad."

def main():
    try:
        peso = float(input("¿Cuál es tu peso en kg? "))
        altura = float(input("¿Cuál es tu altura en metros? "))
    except ValueError:
        print("El peso y la altura tienen que ser numeros") 
        return
    try:
        if peso <= 0 or altura <= 0:
            raise ValueError("El peso y la altura deben ser mayores que 0")
        if altura > 2.5:
            raise ValueError("La altura debe ser menor que 2.5 metros")
        resultado = clasificador_de_resultado(calculadora_imc(peso,altura))
        print(resultado)
    except ValueError as error: 
        print(error)
    
main()

Tu índice de masa corporal es 24.2, tienes un peso normal.

In [ ]:
### S9-1.2 Conversor de temperaturas.
import pandas as pd 
def celsius(temperatura): 
    c = temperatura
    f = round((temperatura * 9/5 + 32),3)
    k = round((temperatura + 273.15),2)
    return c,f,k
def fahrenheit(temperatura): 
    f = temperatura
    c = round(((temperatura - 32) * 5/9),2)
    k = round(((temperatura - 32) * 5/9 + 273.15),2)
    return f,c,k
def kelvin(temperatura): 
    k = temperatura
    f = round(((temperatura - 273.15) * 9/5 + 32),2)
    c = round((temperatura - 273.15),2)
    return k,f,c

def conversor_de_unidades(temperatura,unidades):
    dict_temperaturas = {}
    unidades = unidades.strip().upper() 
    if unidades == "C":
        tempe_entrada, tempe_f, tempe_k = celsius(temperatura)
        dict_temperaturas["Celsius"] = tempe_entrada
        dict_temperaturas["Fahrenheit"] = tempe_f
        dict_temperaturas["Kelvin"]= tempe_k
    elif unidades == "F":
        tempe_entrada, tempe_c, tempe_k = fahrenheit(temperatura)
        dict_temperaturas["Fahrenheit"] = tempe_entrada
        dict_temperaturas["Celsius"] = tempe_c
        dict_temperaturas["Kelvin"]= tempe_k
    elif unidades == "K":
        tempe_entrada, tempe_f, tempe_c = kelvin(temperatura)
        dict_temperaturas["Kelvin"] = tempe_entrada
        dict_temperaturas["Fahrenheit"] = tempe_f
        dict_temperaturas["Celsius"] = tempe_c
    return dict_temperaturas

def main():
    lista_final = []
    cantidad = int(input("¿Cuantas temperaturas quieres convertir?"))
    if cantidad <= 0:
            print("la cantidad de temperaturas tiene que ser mayor que 0")
            return
    unidades = str(input("dime la unidad en la que está, C, F, o K")).strip().upper()
    if unidades not in {"C","K","F"}:
        print("las unidades tienen que ser una de las letras que se indican")
        return
    for n in range(cantidad):
        try:         
            temperatura = float(input(f"dime la temperatura {n +1}"))              
        except ValueError:
            print("La temperatura tiene que ser un numero")
            return 
        if unidades == "K" and temperatura < 0:
            print("los grados Kelvin han de ser un numero mayor o igual que 0")
            return
        lista_final.append(conversor_de_unidades(temperatura,unidades))
    return lista_final

datos = main()  
if datos is None:
    pass 
else:
    data_temperaturas = pd.DataFrame(datos)
    data_temperaturas
data_temperaturas

   Celsius  Fahrenheit  Kelvin
0     43.0       109.4  316.15
1     10.0        50.0  283.15
2     23.0        73.4  296.15

In [2]:
# S9-1.3 Contador de palabras 

def recibe_texto():
    return input("excribe una frase o texto")
def limpia_texto(texto):
    """
    Esta función recibe un texto y lo limpia 
    devolviendo una lista de palabra en minusculas
    y sin ningun tipo de signo
    """
    signos = (("?"," "),("¿"," "),("("," "),
              (")"," "),("."," "),(":"," "),
              ("!"," "),("¡"," "),(";"," "),
              (","," "))
    for viejo,nuevo in signos:
        texto = texto.replace(viejo,nuevo)
    texto = texto.lower()
    palabras = texto.split()
    return palabras 
def contador_de_palabras(palabras):
    """
    Esta funcion recibe un palabras 
    y cuenta las veces que se repite 
    cada palabra y devuele un diccionario 
    con la palabra como calve y 
    el nº que se repite como valor"""

    dict_palabras = {}
    for palabra in palabras:
        if palabra not in dict_palabras:
            dict_palabras[palabra] = 1 
        else:
            dict_palabras[palabra] +=1 
    return dict_palabras
def media_longitud(palabras):
    total = 0
    for palabra in palabras: 
        total += len(palabra)
    media = total/len(palabras)
    return media 
def main():
    texto = recibe_texto()
    texto_limpio = limpia_texto(texto)
    if texto_limpio == []:
        print("Tienes que introducir un texto")
        return
    contador = contador_de_palabras(texto_limpio)
    print(f"El contador {contador}")
    print(f"La media de longitud es: {media_longitud(texto_limpio):.2f}")

main()

El contador {'hola': 2, 'como': 1, 'estas': 2, 'bien': 1}
La media de longitud es: 4.33

In [ ]:
# S9-1.4 Diccionario inverso 

def crea_diccionario():
    diccionario = {}
    try :
        cantidad = int(input("Cuantas claves y valores quieres introducir"))
        if cantidad <= 0:
            print("La cantidad tiene que ser mayor que 0")
            return
    except ValueError:
        print("La cantidad tiene que ser un numero")
        return
    for x in range(cantidad):
        clave = input(f"dame la clave {x+1}")
        valor = input(f"dame el valor{x+1}")
        diccionario[clave] = valor
    return diccionario

def invertir_diccionario(diccionario):
    inverso = {}
    for clave,valor in diccionario.items():
        if valor not in inverso:
            inverso[valor] = [clave]
        else:
            inverso[valor].append(clave)
    for valor in inverso:
        if len(inverso[valor]) == 1:
            inverso[valor] = inverso[valor][0]
    return inverso
def hay_repetidos(dic_inverso):
    for valor,clave in dic_inverso.items():
        if type(clave) == list:
            print(f"valores repetidos {clave} pertenecen a la clave ['{valor}']")
def main():
    original = crea_diccionario()
    if original is None:
        return
    inverso = invertir_diccionario(original)
    print(f"El diccionario original {original}")
    print(f"El diccionario inverso {inverso}")
    hay_repetidos(inverso)
        
main()

El diccionario original {'hola ': '3', 'adios': '5', 'perro': '3', 'magia': '5', 'passa': '8'}
El diccionario inverso {'3': ['hola ', 'perro'], '5': ['adios', 'magia'], '8': 'passa'}
valores repetidos ['hola ', 'perro'] pertenecen a la calve ['3']
valores repetidos ['adios', 'magia'] pertenecen a la calve ['5']

In [37]:
# S9-2.1 Contador y ordenador de palabras de un texto

def ordenar_dict(dict_palabras):
    dict_ordenado = {}
    for clave,valor in sorted(dict_palabras.items()):
        dict_ordenado[clave] = valor
    return dict_ordenado

def agrupar_dict(diccionario):
    dict_agrupado =  {}
    for clave,valor in diccionario.items():
        if clave[0] not in dict_agrupado:
            dict_agrupado[clave[0]] = {}
        dict_agrupado[clave[0]].update({clave:valor})
    return dict_agrupado 

def main(texto):
    diccionario_final = {}
    texto_limpio = limpia_texto(texto)
    agrupado_ordenado = agrupar_dict(
        ordenar_dict(contador_de_palabras(texto_limpio)))
    diccionario_final.update(agrupado_ordenado)
    return diccionario_final

texto = ("""Tú me quieres alba,
me quieres de espumas,
me quieres de nácar.
Que sea azucena
Sobre todas, casta.
De perfume tenue.
Corola cerrada .

Ni un rayo de luna
filtrado me haya.
Ni una margarita
se diga mi hermana.
Tú me quieres nívea,
tú me quieres blanca,
tú me quieres alba.

Tú que hubiste todas
las copas a mano,
de frutos y mieles
los labios morados.
Tú que en el banquete
cubierto de pámpanos
dejaste las carnes
festejando a Baco.
Tú que en los jardines
negros del Engaño
vestido de rojo
corriste al Estrago.

Tú que el esqueleto
conservas intacto
no sé todavía
por cuáles milagros,
me pretendes blanca
(Dios te lo perdone),
me pretendes casta
(Dios te lo perdone),
¡me pretendes alba!

Huye hacia los bosques,
vete a la montaña;
límpiate la boca;
vive en las cabañas;
toca con las manos
la tierra mojada;
alimenta el cuerpo
con raíz amarga;
bebe de las rocas;
duerme sobre escarcha;
renueva tejidos
con salitre y agua:

Habla con los pájaros
y lévate al alba.
Y cuando las carnes
te sean tornadas,
y cuando hayas puesto
en ellas el alma
que por las alcobas
se quedó enredada,
entonces, buen hombre,
preténdeme blanca,
preténdeme nívea,
preténdeme casta.""")

main(texto)

{'a': {'a': 3,
  'agua': 1,
  'al': 2,
  'alba': 4,
  'alcobas': 1,
  'alimenta': 1,
  'alma': 1,
  'amarga': 1,
  'azucena': 1},
 'b': {'baco': 1,
  'banquete': 1,
  'bebe': 1,
  'blanca': 3,
  'boca': 1,
  'bosques': 1,
  'buen': 1},
 'c': {'cabañas': 1,
  'carnes': 2,
  'casta': 3,
  'cerrada': 1,
  'con': 4,
  'conservas': 1,
  'copas': 1,
  'corola': 1,
  'corriste': 1,
  'cuando': 2,
  'cubierto': 1,
  'cuerpo': 1,
  'cuáles': 1},
 'd': {'de': 8, 'dejaste': 1, 'del': 1, 'diga': 1, 'dios': 2, 'duerme': 1},
 'e': {'el': 4,
  'ellas': 1,
  'en': 4,
  'engaño': 1,
  'enredada': 1,
  'entonces': 1,
  'escarcha': 1,
  'espumas': 1,
  'esqueleto': 1,
  'estrago': 1},
 'f': {'festejando': 1, 'filtrado': 1, 'frutos': 1},
 'h': {'habla': 1,
  'hacia': 1,
  'haya': 1,
  'hayas': 1,
  'hermana': 1,
  'hombre': 1,
  'hubiste': 1,
  'huye': 1},
 'i': {'intacto': 1},
 'j': {'jardines': 1},
 'l': {'la': 3,
  'labios': 1,
  'las': 7,
  'lo': 2,
  'los': 4,
  'luna': 1,
  'lévate': 1,
  'límpiate': 1},
 'm': {'mano': 1,
  'manos': 1,
  'margarita': 1,
  'me': 10,
  'mi': 1,
  'mieles': 1,
  'milagros': 1,
  'mojada': 1,
  'montaña': 1,
  'morados': 1},
 'n': {'negros': 1, 'ni': 2, 'no': 1, 'nácar': 1, 'nívea': 2},
 'p': {'perdone': 2,
  'perfume': 1,
  'por': 2,
  'pretendes': 3,
  'preténdeme': 3,
  'puesto': 1,
  'pájaros': 1,
  'pámpanos': 1},
 'q': {'que': 6, 'quedó': 1, 'quieres': 6},
 'r': {'rayo': 1, 'raíz': 1, 'renueva': 1, 'rocas': 1, 'rojo': 1},
 's': {'salitre': 1, 'se': 2, 'sea': 1, 'sean': 1, 'sobre': 2, 'sé': 1},
 't': {'te': 3,
  'tejidos': 1,
  'tenue': 1,
  'tierra': 1,
  'toca': 1,
  'todas': 2,
  'todavía': 1,
  'tornadas': 1,
  'tú': 8},
 'u': {'un': 1, 'una': 1},
 'v': {'vestido': 1, 'vete': 1, 'vive': 1},
 'y': {'y': 5}}

In [83]:
# S9-2.2 Converion de tipos de datos
import ast
def recibe_lista():
    lista  = []
    entrada = input("Dame una lista de numero, tanto en letra como numeros")
    lista = ast.literal_eval(entrada)
    return lista 

def conversor_float(lista):
    lista_de_floats = []
    lista_no_floats = []
    for x in lista: 
        if isinstance( x, (tuple,list)):
                for i in x:
                        if isinstance(i,(tuple,list)):
                            floats, no_floats = conversor_float(i)
                            lista_de_floats.extend(floats)
                            lista_no_floats.extend(no_floats)
                        else:
                            try:
                                num = float(i)
                                lista_de_floats.append(num)
                            except ValueError:
                                 lista_no_floats.append(i)                                                              
        else:
            try:
                num = float(x)
                lista_de_floats.append(num)
            except ValueError:
                 lista_no_floats.append(x)
    return lista_de_floats, lista_no_floats

def main():
    return conversor_float(
                recibe_lista())

main()

([4.5, 2000.0, 8.0, 3.0, 6.7, 5.0, 6.0, 7.8],
 ['hola', 'nueve', '7/2', 'mal', 'texto'])

In [52]:
# S9-3.1 Generador de contraseñas 
import string as st
import numpy as np
import pyperclip as pyp

def longitud_de_caracteres():
    longitud =  int(input("Cunatos caracteres quieres que tenga la contraseña?"
                         " Tiene que ser minimo 8"))
    while longitud < 8 :
        print("la contraseña tiene que tener minimo 8 caracteres")
        longitud =  int(input("Cunatos caracteres quieres que tenga la contraseña?"
                         " Tiene que ser minimo 8"))
    return longitud

def tipo_de_caracteres():
    mayusculas = input("quieres que contanga myusculas, si o no ?").lower()
    if mayusculas == "si" or mayusculas == "sí":
        mayusculas = True
    else:
        mayusculas = False
    minusculas = input("quieres que contanga minúsculas, si o no ?").lower()
    if minusculas == "si" or minusculas == "sí":
        minusculas = True
    else:
        minusculas = False
    numeros = input("quieres que contanga números, si o no ?").lower()
    if numeros == "si" or numeros == "sí":
        numeros = True
    else:
        numeros = False
    signos = input("quieres que contanga signos, si o no ?").lower()
    if signos == "si" or signos == "sí":
        signos = True
    else:
        signos = False
    return mayusculas,minusculas,numeros,signos

def validador_de_caracteres():
    while True:
        mayusculas,minusculas,numeros,signos = tipo_de_caracteres()
        if mayusculas or minusculas or numeros or signos:
            break
        print("La contraseña tiene que tener mínimo un tipo de los caracteres")
    return mayusculas,minusculas,numeros,signos     

def generador_contraseñas():
    list_contraseña = []
    mayus = [] 
    mayus.extend(st.ascii_uppercase)
    minus = []
    minus.extend(st.ascii_lowercase)
    nums = []
    nums.extend(st.digits)
    sign = ["-","_","$","#","?","¿","*","€","@","&","!","¡","%"]
    longitud = longitud_de_caracteres()
    mayusculas,minusculas,numeros,signos = validador_de_caracteres()
    caracteres = [(mayusculas,mayus),(minusculas,minus),(numeros,nums),(signos,sign)]
    diponibles = []
    for x,i in caracteres:
        if x == True:
                list_contraseña.extend(np.random.choice
                              (i))
                diponibles.extend(i)          
    faltan = longitud - len(list_contraseña)
    for x in range(faltan):
        list_contraseña.extend(np.random.choice(diponibles))
    return list_contraseña

def main():
    contraseña = generador_contraseñas()
    np.random.shuffle(contraseña)
    contraseña = "".join(contraseña)
    pyp.copy(contraseña)
    print("Contraseña copiada en el portapapeles")
    print(f"La contraseña es: {contraseña}")

main()

Contraseña copiada en el portapapeles
La contraseña es: C$k&B?p€ZV7z

In [177]:
#S9-3.2 Procesamiento simple de datos. 

import pandas as pd

df_historico_partidos = pd.read_csv(r"C:\Users\Usuario\Downloads\historic partits.txt",
                                    sep="\t",
                                    header=None,
                                    names=["Equipo local","Resultado","Equipo visitante"])
df_historico_partidos[["Goles local","Goles visitante"]] =  df_historico_partidos["Resultado"].str.split("-", expand=True)
df_historico_partidos["Goles local"] = df_historico_partidos["Goles local"].astype(int)
df_historico_partidos["Goles visitante"] = df_historico_partidos["Goles visitante"].astype(int)
equipos = pd.concat([df_historico_partidos["Equipo local"],df_historico_partidos["Equipo visitante"]]).unique()
df_resultado_equipos = pd.DataFrame(equipos,columns=["Equipo"])
df_resultado_equipos["Goles a favor"] = 0
df_resultado_equipos["Goles en contra"] = 0
df_resultado_equipos["Puntos"] = 0

goles_local = df_historico_partidos.groupby("Equipo local")["Goles local"].sum()
goles_visitante = df_historico_partidos.groupby("Equipo visitante")["Goles visitante"].sum()
goles_no_local = df_historico_partidos.groupby("Equipo local")["Goles visitante"].sum()
goles_no_visitante = df_historico_partidos.groupby("Equipo visitante")["Goles local"].sum()

df_resultado_equipos["Goles a favor"] = df_resultado_equipos["Equipo"].map(goles_local.add(goles_visitante, fill_value=0))
df_resultado_equipos["Goles en contra"] = df_resultado_equipos["Equipo"].map(goles_no_local.add(goles_no_visitante, fill_value=0))
def contador_de_puntos_local(fila):
    if fila["Goles local"]>fila["Goles visitante"]:
        return 3
    elif fila["Goles local"]<fila["Goles visitante"]:
        return 0
    else:
        return 1

def contador_de_puntos_visitante(fila):
    if fila["Goles visitante"]>fila["Goles local"]:
        return 3
    elif fila["Goles visitante"]<fila["Goles local"]:
        return 0
    else:
        return 1

df_historico_partidos["Puntos local"] = 0
df_historico_partidos["Puntos visitante"] = 0
df_historico_partidos["Puntos local"] = df_historico_partidos.apply(contador_de_puntos_local,axis=1)
df_historico_partidos["Puntos visitante"] = df_historico_partidos.apply(contador_de_puntos_visitante,axis=1)

puntos_local = df_historico_partidos.groupby("Equipo local")["Puntos local"].sum()
puntos_visitante = df_historico_partidos.groupby("Equipo visitante")["Puntos visitante"].sum()

df_resultado_equipos["Puntos"] = df_resultado_equipos["Equipo"].map(puntos_local.add(puntos_visitante, fill_value=0))
df_resultado_equipos

                 Equipo  Goles a favor  Goles en contra  Puntos
0               Manlleu            106              118      57
1            Vilafranca            157              172      72
2                  Olot            132              144      64
3              Cornellà            147              146      82
4            Cerdanyola            117              133      56
5           Sant Andreu            123              134      62
6          FC Barcelona            125              115      73
7            Granollers            122              117      67
8                  Prat            106              111      56
9            Llagostera            159              142      94
10             Figueres            161              154      79
11               Europa             93               93      41
12             Terrassa            147              164      74
13        Reus Deportiu            119              111      68
14            Girona FC            139               94      96
15             Badalona            134              124      68
16             Sabadell            141              121      85
17      Lleida Esportiu            129              133      75
18  Nàstic de Tarragona            130              148      68
19         RCD Espanyol            131              144      80

In [178]:
print("El equipo con mas goles a favor")
df_resultado_equipos.groupby("Equipo")["Goles a favor"].max().sort_values(ascending=False).head(1)

El equipo con mas goles a favor

Equipo
Figueres    161
Name: Goles a favor, dtype: int64

In [179]:
print("El equipo con mas goles en contra")
df_resultado_equipos.groupby("Equipo")["Goles en contra"].max().sort_values(ascending=False).head(1)

El equipo con mas goles en contra

Equipo
Vilafranca    172
Name: Goles en contra, dtype: int64